#By Wdsj.net 如遇到问题，你可以前往 https://bbs.wdsj.net/t/dev 进行反馈

CONFIG_SERVER_GROUP: global

config:
  #调试模式
  debug: false
  #是否将已被触发过的盔甲架缓存（生成环境建议开启，开发调试建议关闭
  #设置为true将保存第一次触发的解析内容作为缓存，为false则每次都重新解析
  cache: true

  #功能的前缀名
  component:
    COMMAND: "command"
    MESSAGE: "message"